# Generated by Django 4.0.4 on 2022-04-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_library', '0003_song_artist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='song',
        ),
        migrations.AddField(
            model_name='album',
            name='song',
            field=models.ManyToManyField(to='music_library.song'),
        ),
    ]
